version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - pip install boto3
  build:
    commands:
      - echo Entered the build phase...
      - mkdir -p generated-cicd-templates
      - python buildspec/generate-cicd-templates.py
  post_build:
    commands:
      - aws s3 sync generated-cicd-templates s3://${S3Bucket}/generated-cicd-templates/ --delete
      - aws s3 sync pipeline-templates s3://${S3Bucket}/pipeline-templates/ --delete
artifacts:
  files:
    - '**/*'
  base-directory: 'generated-cicd-templates'
  discard-paths: yes